version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:6
    container_name: social-network-mongo-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-dev:/data/db
    environment:
      MONGO_INITDB_DATABASE: social-network
    networks:
      - social-network-network-dev

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: social-network-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data-dev:/data
    command: redis-server --appendonly yes
    networks:
      - social-network-network-dev

  # Backend API (Development with hot reload)
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: social-network-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/social-network
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-jwt-secret-change-in-production
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo
      - redis
    networks:
      - social-network-network-dev
    command: npm run dev

  # Frontend Application (Development with hot reload)
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    container_name: social-network-frontend-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:5000/api
      - NEXT_PUBLIC_FIREBASE_API_KEY=${NEXT_PUBLIC_FIREBASE_API_KEY}
      - NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
      - NEXT_PUBLIC_FIREBASE_PROJECT_ID=${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
      - NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
      - NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}
      - NEXT_PUBLIC_FIREBASE_APP_ID=${NEXT_PUBLIC_FIREBASE_APP_ID}
    volumes:
      - .:/app
      - nextjs-build:/app/.next
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - social-network-network-dev
    command: npm run dev

volumes:
  mongo-data-dev:
    driver: local
  redis-data-dev:
    driver: local
  nextjs-build:
networks:
  social-network-network-dev:
    driver: bridge 